Map<String, String> room_inspection_deductions = {
  "Hat Shelf": "-2",
  "Hangers/Hooks": "-2",
  "Shoe Display": "-2",
  "Overhead Storage": "-2",
  "Countertop/Sink": "-3",
  "Rifle Rack": "-1",
  "Towel Rack": "-1",
  "Mirrors": "-2",
  "Valet Cabinets/Laundry": "-2",
  "Bed/Flat/Issues Comforter": "-3",
  "Memorabilia/Shelves/Desk": "-5",
  "Bulletin Boards": "-2",
  "Chair/Under Desk": "-3",
  "Alcove/Exterior": "-3",
  "Walls/Carpet": "-2",
  "Trash Can": "-3",
  "Lights": "-2",
  "Windows/Runner": "-2",
  "Door Closed": "-10",
  "Unauthorized Monitor/TV": "-15",
  "Unauthorized Wall Ornamentation": "-15",
  "Unauthorized Room Arrangement": "-20",
  "Security Violation": "-25"
};

Map<String, String> pai_deductions = {
  "Appropriate Uniform": "-100",
  "Proxy Card": "-10",
  "Bearing": "-10",
  "Hair": "-10",
  "Facial Hair": "-10",
  "Cosmetics": "-3",
  "Rank/Rope": "-5",
  "Accoutrement": "-5",
  "Tie/Tie Tab": "-10",
  "Unserviceable Uniform": "-10",
  "Nail Polish": "-5",
  "Nails Unpresentable": "-2",
  "Unauthorized Accessories": "-2",
  "Miscellaneous Infraction": "-2",
  "Belt": "-5",
  "Gig Line": "-2",
  "Socks": "-2",
  "Shoes": "-2",
};
