// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJcwR9t2NB1vazZRqVpR9QlgqdG7Y_Cf8',
    appId: '1:150025587834:web:8caeef926fbf7fdedc7fc3',
    messagingSenderId: '150025587834',
    projectId: 'falconnet-376419',
    authDomain: 'falconnet-376419.firebaseapp.com',
    storageBucket: 'falconnet-376419.appspot.com',
    measurementId: 'G-GD4WMMLTV2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDxiV746uAou1wednXtsLpICFuOJ0rZEw4',
    appId: '1:150025587834:android:c983d78fa2d81252dc7fc3',
    messagingSenderId: '150025587834',
    projectId: 'falconnet-376419',
    storageBucket: 'falconnet-376419.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPPqz2JS-IqUkMszlLNFGUEwcB362Cl20',
    appId: '1:150025587834:ios:4aaf905fd4560438dc7fc3',
    messagingSenderId: '150025587834',
    projectId: 'falconnet-376419',
    storageBucket: 'falconnet-376419.appspot.com',
    iosBundleId: 'com.arkwerk.falconnet',
  );
}
